### ISSUE TITLE
Adjust gas before confirming transaction or contract interaction

### ISSUE THREAD

**Issue by SeqSEE** [TheLindaProjectInc/MetriMask#12]
![image](https://user-images.githubusercontent.com/15011102/130230638-fe93cb39-7cdd-43fe-86b0-ea724dd85bd1.png)

Allow the user to adjust the gas and value before confirming.

**Comment by nibbles83** [comment]
https://github.com/TheLindaProjectInc/MetriMask/commit/25d8f6758916cd25ad39c2b222b92024843b2bad should enable this.
