### ISSUE TITLE
Max Transaction fee wrong

### ISSUE THREAD

**Issue by SeqSEE** [TheLindaProjectInc/MetriMask#16]
![image](https://user-images.githubusercontent.com/15011102/130335194-d4669e76-e42e-4a44-a275-2dfa33cb0af5.png)

**Comment by nibbles83** [comment]
This should fix it.
https://github.com/TheLindaProjectInc/MetriMask/commit/8e7510954859536450deb53811c77e5f28cd9119

**Comment by nibbles83** [comment]
Seems to be ok, closing this one.
