### ISSUE TITLE
Add pending transactions to the Transactions tab in account

### ISSUE THREAD

**Issue by SeqSEE** [TheLindaProjectInc/MetriMask#17]
Add transactions that are pending to the transactions list from both sendtocontract and sending regular transactions. Right now the transactions tab doesn't update until the transaction was confirmed, but it definitely already got the txid as a response before it was ever confirmed.

**Comment by nibbles83** [comment]
This has been partially fixed, the TX tab will now display 0 conf transactions rather then fail to load any tx's.
Will look to further build on this with maybe some sort of infinite scrolling gif or something to indicate a pending 0 confirm tx.

**Comment by nibbles83** [comment]
Pending transactions will now display differently to confirmed transactions in v1.0.7 onwards.
