### ISSUE TITLE
issue sending MRX when using max send.

### ISSUE THREAD

**Issue by Funkydog-nl** [TheLindaProjectInc/MetriMask#22]
Seems to be an issue with the fee deduction while trying to send MRX.
Example, the wallet holds 
3,686.17522607 and I want to send it out using MAX amount. It deducts the amount to: 3,684.30922607 this is roughly 1.866 MRX which is too low for MRX fees.  when I reduce it to 3,683,60922607 it will send out properly leaving no coins in the wallet.

**Comment by Funkydog-nl** [comment]
yep tested it this morning and indeed the deducted fee is incorrect.

3686.17522607 input
 
MetriMask reduces it to

3684.30922607

which is 1.866 fee which is too low as minimal fee is 2.25
When I manually adjust fee to: 3683.92522607 it will send out. So fee calculation needs a fix

**Comment by nibbles83** [comment]
https://github.com/TheLindaProjectInc/MetriMask/commit/646d7f135ee31a6f46d4cfde90619df69484ff0f should fix this issue.

**Comment by nibbles83** [comment]
This now works in v1.0.5. release due shortly.
