### ISSUE TITLE
Wrong GasPrice displayed

### ISSUE THREAD

**Issue by SeqSEE** [TheLindaProjectInc/MetriMask#3]
![image](https://user-images.githubusercontent.com/15011102/130183084-8259fe1e-6dc1-4da3-8b8b-a896ac0ca72d.png)

The contract call was done as so:

```
window.metrimask.rpcProvider.rawCall(
  "sendtocontract",
  [
    contract,
    encoded.replace("0x", ""),
    tmp.value,
    250000,
    5000,
  ]
)
```

**Comment by nibbles83** [comment]
Should be fixed with this.

https://github.com/TheLindaProjectInc/MetriMask/commit/16ee1bbf91fdec677b4293b06e0e1d0ac0a328fe

**Comment by nibbles83** [comment]
Seems to be ok now.
