### ISSUE TITLE
Can we remove the scroll bar?

### ISSUE THREAD

**Issue by SeqSEE** [TheLindaProjectInc/MetriMask#5]
![image](https://user-images.githubusercontent.com/15011102/130223769-1ff37788-0d9d-4c84-a828-3af9536b85d0.png)

Really only a cosmetic preference, but I think MetriMask could look much cleaner if the scroll bar were removed.

**Comment by SeqSEE** [comment]
![image](https://user-images.githubusercontent.com/15011102/130224040-6a83b8e0-327b-4685-b6bf-19478c4e02a4.png)

**Comment by nibbles83** [comment]
The below commit will remove this.
https://github.com/TheLindaProjectInc/MetriMask/commit/81a0709cf53be758bc5e9fd7b09c7c78a3543cca
