### ISSUE TITLE
Copy to clipboard for receive

### ISSUE THREAD

**Issue by SeqSEE** [TheLindaProjectInc/MetriMask#6]
![image](https://user-images.githubusercontent.com/15011102/130224248-87e9a98c-f5fe-485b-aa97-a74f984d9151.png)
It would be extremely useful to have a copy to clipboard button/option.

**Comment by nibbles83** [comment]
Added copy button 
https://github.com/TheLindaProjectInc/MetriMask/commit/8f2da6630941f9a5f55e28d36adba8eebd9fe1e1
