### ISSUE TITLE
Expanded view/extended window

### ISSUE THREAD

**Issue by SeqSEE** [TheLindaProjectInc/MetriMask#9]
Having a popout/fullscreen window to look at account information is really useful. I included some images of what MetaMask does to provide that functionality.

![image](https://user-images.githubusercontent.com/15011102/130225034-02b2263e-bc50-4528-b8ff-1200055918b8.png)
![image](https://user-images.githubusercontent.com/15011102/130225171-b15d079c-341c-47ce-bd32-0f8c49af5f23.png)

**Comment by nibbles83** [comment]
Should be sorted with this.
https://github.com/TheLindaProjectInc/MetriMask/commit/fc05e8674df89d679f03564dbc5aba7d44c9ef79
